### ISSUE TITLE
Get Room Name and Username in SessionActivity

### ISSUE THREAD

**Issue by c0d3ster** [njtrettel/CollabQ#7]
We need to grab the Room Name from the SocketController and the username from the main activity in the SessionActivity's onCreateView().  We also need to initialize the SocketController in this method first.  Room Name -> Q tab title
Username -> q_list_item when queueing a song

**Comment by njtrettel** [comment]
Done using `putExtra()` and `getExtra()` when creating Intent to move to the SessionActivity
